Start study: 1G Braking Friday, August 21, 2026 11:26:11 PM
End study: 1G Braking Friday, August 21, 2026 11:26:14 PM
Start study: Downhill Friday, August 21, 2026 11:26:56 PM
End study: Downhill Friday, August 21, 2026 11:27:03 PM
